server:
  port: 8082

spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    schema: classpath:/static/schema.sql, classpath:/static/data.sql
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext

  servlet:
    multipart:
      max-file-size: 20MB

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
        readTimeout: 160000000

eureka:
  instance:
    instance-id: sport-location-service-api

spsa:
  connect:
    url: http://localhost:8083/
