spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 961356669262-1bse5nevvpnd0g6saj8uicbe44j2idbd.apps.googleusercontent.com
            client-secret: jOcUAcRkpFzBEnq88J85s0To
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            clientId: 1111459259195237
            clientSecret: 63fe7d9ec275997baf31eebed028fe20
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
