server:
  port: 8083
#  ssl:
#    key-alias: SPSA
#    key-store-type: JKS
#    key-store-password: password
#    key-store: classpath:keystore.jks

spring:
  profiles:
    active: security
  h2:
    console:
      enabled: true
      path: /h2db
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
    schema: classpath:/static/schema.sql, classpath:/static/data.sql
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  servlet:
    multipart:
      max-file-size: 20MB

eureka:
  instance:
    instance-id: sport-partner-service-api

slsa:
  connect:
    url: http://localhost:8082/

spsa:
  connect:
    url: http://localhost:8083/

mail-server:
  connect:
    url: http://localhost:8084/

feign:
  client:
    config:
      default:
        connectTimeout: 160000000
